#!/usr/bin/python

INFECTION_CHANCE = 0.3
CHANCE_OF_MUTATION_ON_INFECTION = 0.15
CHANCE_OF_MUTATION_ON_NOTHING = 0.01
CHANCE_OF_MUTATION_ON_REPRODUCTION = 0.2
PARAZITE_FIGHT_CHANCE = 0.3
RESISTANCE_AFTER_RECOVERY = 1
BASE_CHANCE_OF_HEALING = 0.13
