#!/usr/bin/python

INFECTION_CHANCE = 0.4
CHANCE_OF_MUTATION_ON_INFECTION = 0.4
CHANCE_OF_MUTATION_ON_NOTHING = 0.5
CHANCE_OF_MUTATION_ON_REPRODUCTION = 0
PARAZITE_FIGHT_CHANCE = 0
TRANSMISSION_OF_RESISTANCE_PROB = 0
BASE_CHANCE_OF_HEALING = 0
