#!/usr/bin/python

INFECTION_CHANCE = 0.4
CHANCE_OF_MUTATION_ON_INFECTION = 0
CHANCE_OF_MUTATION_ON_NOTHING = 0
CHANCE_OF_MUTATION_ON_REPRODUCTION = 0
PARAZITE_FIGHT_CHANCE = 0
RESISTANCE_AFTER_RECOVERY = 0
BASE_CHANCE_OF_HEALING = 0.13
