# resistance = 

#SIMULATION
SIMULATION_TIME = 10

#GUI
DELTA_TIME = 1.0 / 60.0
MAX_BALL_SPEED = 100
BASE_COLOR = [0,0,1]
SPEC_BASE_COLOR = [0,0.5,.5]
POS_X = 0
POS_Y = 0

#MAIN
NB_SAINS = 100
NB_PARASITE = 1 
MAX_VELOCITY= 1
MAX_VIRULANCE= 1
ALL_NIGHT_LONG = 0
HEALTHY_ROOF = 1
MIN_SIZE_FOR_DATA = 40 * 1000  #pour avoir mesure en kb 
TEST_THEORY = 1

#INDIVIDUAL
DYING_PROB = 0.13    #max 0.5
STOCK_DYING_PROB = 0.13
ROOF_DYING_PROB = 0.2
REPRODUCTION_PROB = 0.13
STOCK_REPRODUCTION_PROB = 0.13
BOTTOM_REPRODUCTION_PROB = 0.15
TRADE_OFF = 'leo'

#HEALTHY
GENERATION_RESISTANCE = 1

#PARAZITE
BASE_FITNESS = 0.8
MAX_FITNESS = 1.8
MAX_FITNESS_CHANGE_ON_INFECTION = 0.2   #max 0.5
MAX_FITNESS_CHANGE_ON_NOTHING = 0.1   #max 0.5
MAX_FITNESS_CHANGE_ON_REPRODUCTION = 0.2 #max 0.5

#equations
compteur_id = 1
last_clock = 0
nb_coll = 0
mean_vir = 0
mean_trans = 0
mean_recov = 0
